services:
  windows:
    image: dockurr/windows
    container_name: windows10
    environment:
      VERSION: "win10"
      LANGUAGE: "en-US"
      TZ: "America/New_York"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      REGION: "en-US"      # Defining the region as US
      KEYBOARD: "us"       # Defining the keyboard layout as US
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/user/example:/shared
      - /userdata/windows:/userdata/windows # Adding volume for /userdata/windows
    stop_grace_period: 2m
